# Generated by Django 5.0.1 on 2024-02-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizanswer",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
    ]
