# Generated by Django 5.0.1 on 2024-02-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item2", "0002_quizanswer_is_correct"),
    ]

    operations = [
        migrations.CreateModel(
            name="quizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("answers", models.ManyToManyField(to="item2.quizanswer")),
            ],
        ),
    ]
