# Generated by Django 5.0.1 on 2024-04-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item2", "0008_alter_quiz_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="subject",
            field=models.CharField(default="", max_length=100),
        ),
    ]
